Repository zuplo/zudoku, pull requests merged in 2024-10, with the labels that each got.

#253 Fixed playground width
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/ResponseTab.tsx
Labels: bug

#254 Remove "Go home" link
  packages/zudoku/src/lib/components/ErrorPage.tsx
Labels: feature

#255 Fix Windows compatibility
  packages/zudoku/src/vite/config.ts
Labels: bug

#265 Fix dev SSR when using context in custom pages
  packages/zudoku/package.json
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/lib/plugins/custom-pages/index.tsx
  packages/zudoku/src/types.d.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/src/vite/plugin-custom-pages.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/tsconfig.json
  packages/zudoku/vite.config.ts
Labels: bug

#264 Proxy entry client file through express middleware
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#266 Allow custom banner color
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/components/Banner.tsx
  packages/zudoku/src/lib/core/DevPortalContext.ts
Labels: feature

#267 Add top nav/header slotlets, mark as unsafe, allow to be component
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/SlotletProvider.tsx
Labels: feature

#268 fix search on mobile
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
Labels: bug

#270 Base path fixes
  packages/zudoku/src/cli/dev/handler.ts
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#271 Join base path instead of concatenating
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#273 Better placement of search
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/Search.tsx
Labels: bug

#274 Use correct prose class in custom pages
  packages/zudoku/src/lib/plugins/custom-pages/CustomPage.tsx
Labels: bug

#275 Treat .md files as MDX
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: feature

#276 Prepend base path in MDX media
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: bug

#277 Fix mobile nav scroll
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
Labels: bug

#279 Sidebar fixes
  packages/zudoku/src/app/main.css
  packages/zudoku/src/config/validators/InputSidebarSchema.ts
  packages/zudoku/src/config/validators/SidebarSchema.ts
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
Labels: bug

#302 Merge pr
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#278 Search as vite plugin
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/types.d.ts
  packages/zudoku/src/vite/plugin-search.ts
  packages/zudoku/src/vite/plugin.ts
Labels: feature, refactor

#305 Add authentication type `openid`
  packages/zudoku/src/config/validators/validate.ts
Labels: feature
