Repository zuplo/zudoku, pull requests merged in 2024-12, with the labels that each got.

#399 Hide dark themed logo in light mode
  packages/zudoku/src/lib/components/Header.tsx
Labels: bug

#402 Schema post processors
  packages/config/src/config.ts
  packages/zudoku/package.json
  packages/zudoku/src/cli/common/logger.ts
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLClient.tsx
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
  pnpm-lock.yaml
Labels: feature, refactor

#403 Add `removeExtensions` and `removePaths` processors
  .github/workflows/build.yaml
  .gitignore
  packages/zudoku/package.json
  packages/zudoku/src/lib/oas/parser/upgrade/index.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeExtensions.test.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeExtensions.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removePaths.test.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removePaths.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/traverse.ts
  packages/zudoku/src/lib/util/traverse.ts
  packages/zudoku/src/vite/config.test.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/src/vite/plugin-docs.test.ts
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: feature

#412 Added withZuplo configuration helper
  packages/zudoku/package.json
  packages/zudoku/src/zuplo/with-zuplo.ts
Labels: feature

#407 Use react-refresh ignored exports
  package.json
  packages/zudoku/package.json
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/markdown/index.tsx
  patches/@vitejs__plugin-react@4.3.1.patch
  pnpm-lock.yaml
Labels: skip-changelog

#417 Fix absolute + basepath links and `mailto` links
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: bug

#420 Add excerpt to meta description in docs
  packages/zudoku/package.json
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/markdown/index.tsx
  packages/zudoku/src/vite/plugin-mdx.ts
  pnpm-lock.yaml
Labels: feature

#423 Dev server: Redirect to base path if missing
  packages/zudoku/src/vite/dev-server.ts
Labels: feature

#422 Add vendor chunking
  packages/zudoku/src/app/entry.client.tsx
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/vite/config.ts
Labels: feature

#421 Add workaround for version skew
  packages/zudoku/src/app/entry.client.tsx
Labels: bug

#415 Fix Vercel output path
  docs/vercel.json
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/output.ts
Labels: bug

#429 require path params
  packages/zudoku/src/lib/plugins/openapi/playground/PathParams.tsx
Labels: bug

#426 add catalog plugin
  examples/godzilla-inc/.gitignore
  examples/godzilla-inc/package.json
  examples/godzilla-inc/pages/burger.webp
  examples/godzilla-inc/pages/documentation/test.mdx
  examples/godzilla-inc/pages/general.mdx
  examples/godzilla-inc/public/burger.webp
  examples/godzilla-inc/schema/destructive.json
  examples/godzilla-inc/schema/entertainment.json
  examples/godzilla-inc/schema/logistics.json
  examples/godzilla-inc/schema/operational.json
  examples/godzilla-inc/tsconfig.json
  examples/godzilla-inc/zudoku.config.ts
  packages/zudoku/package.json
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/api-catalog/Catalog.tsx
  packages/zudoku/src/lib/plugins/api-catalog/index.tsx
  packages/zudoku/src/types.d.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: feature

#437 Add support for custom fonts
  docs/pages/configuration/customization.md
  docs/zudoku.config.tsx
  packages/zudoku/src/app/tailwind.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-theme-css.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/vite.standalone.config.ts
Labels: feature

#439 Fix CSS `@import` order
  packages/zudoku/src/vite/plugin-theme-css.ts
Labels: bug

#444 Remove manual chunking
  packages/zudoku/src/vite/config.ts
Labels: bug

#445 Remove syntax highlighter test
  packages/zudoku/src/lib/components/SyntaxHighlight.tsx
Labels: skip-changelog

#442 Add Inkeep search to docs
  docs/zudoku.config.tsx
Labels: docs, skip-changelog

#471 update nx to latest
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: dependencies

#477 Updated react-helmet-async
  packages/zudoku/package.json
  pnpm-lock.yaml
Labels: dependencies

#479 Additional dependency updates for react 19
  examples/godzilla-inc/package.json
  examples/many-apis/package.json
  examples/with-auth0/package.json
  examples/with-config/package.json
  examples/with-openapi-json/package.json
  examples/with-openapi-yaml/package.json
  examples/with-vite-config/package.json
  examples/with-zuplo/package.json
  package.json
  packages/zudoku/package.json
  pnpm-lock.yaml
Labels: dependencies
