Repository zuplo/zudoku, pull requests merged in 2024-11, with the labels that each got.

#319 Use suspense + react query
  packages/zudoku/src/lib/authentication/components/CallbackHandler.tsx
  packages/zudoku/src/lib/errors/ErrorAlert.tsx
  packages/zudoku/src/lib/util/invariant.ts
Labels: bug

#320 Fix capitalization and spelling of programming languages and product names
  CHANGELOG.md
  docs/pages/docs/configuration/vite-config.md
  docs/pages/docs/markdown/overview.md
  docs/src/PreviewBanner.tsx
  packages/create-zudoku-app/templates/default/js/README-template.md
  packages/create-zudoku-app/templates/default/ts/README-template.md
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  website/src/app/components/Footer.tsx
  website/src/app/components/page.tsx
Labels: bug

#321 Zudoku UI
  packages/zudoku/package.json
  packages/zudoku/scripts/hack-worker.mjs
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/internal.ts
  packages/zudoku/src/lib/plugins/api-keys/CreateApiKey.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/PlaygroundDialog.tsx
  packages/zudoku/src/lib/ui/Accordion.tsx
  packages/zudoku/src/lib/ui/Alert.tsx
  packages/zudoku/src/lib/ui/AlertDialog.tsx
  packages/zudoku/src/lib/ui/AspectRatio.tsx
  packages/zudoku/src/lib/ui/Badge.tsx
  packages/zudoku/src/lib/ui/Breadcrumb.tsx
  packages/zudoku/src/lib/ui/Button.tsx
  packages/zudoku/src/lib/ui/Carousel.tsx
  packages/zudoku/src/lib/ui/Checkbox.tsx
  packages/zudoku/src/lib/ui/Collapsible.tsx
  packages/zudoku/src/lib/ui/Dialog.tsx
  packages/zudoku/src/lib/ui/Form.tsx
  packages/zudoku/src/lib/ui/HoverCard.tsx
  packages/zudoku/src/lib/ui/Label.tsx
  packages/zudoku/src/lib/ui/Pagination.tsx
  packages/zudoku/src/lib/ui/Popover.tsx
  packages/zudoku/src/lib/ui/Progress.tsx
  packages/zudoku/src/lib/ui/RadioGroup.tsx
  packages/zudoku/src/lib/ui/ScrollArea.tsx
  packages/zudoku/src/lib/ui/Select.tsx
  packages/zudoku/src/lib/ui/Skeleton.tsx
  packages/zudoku/src/lib/ui/Slider.tsx
  packages/zudoku/src/lib/ui/Switch.tsx
  packages/zudoku/src/lib/ui/Textarea.tsx
  packages/zudoku/src/lib/ui/Toggle.tsx
  packages/zudoku/src/lib/ui/ToggleGroup.tsx
  packages/zudoku/src/lib/ui/Tooltip.tsx
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/tsconfig.json
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: feature

#326 Allow outside import file change
  packages/zudoku/src/vite/plugin-config-reload.ts
Labels: bug

#331 Expose params
  packages/zudoku/src/lib/components/SlotletProvider.tsx
  packages/zudoku/src/lib/plugins/custom-pages/CustomPage.tsx
  packages/zudoku/src/lib/util/useExposedProps.tsx
Labels: feature

#355 Fix initial state of collapsible
  packages/zudoku/src/lib/plugins/openapi/CollapsibleCode.tsx
  packages/zudoku/src/lib/util/useIsomorphicLayoutEffect.ts
Labels: bug

#353 Show array type descriptor in params
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
Labels: bug

#354 GraphQL hydration
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/lib/plugins/openapi/client/createMemoryClient.ts
  packages/zudoku/src/lib/plugins/openapi/client/createWorkerClient.ts
Labels: bug

#356 Add `ActionButton` component
  packages/zudoku/src/lib/ui/ActionButton.tsx
Labels: feature

#357 Use `Button` component for theme icon
  packages/zudoku/src/lib/components/Header.tsx
Labels: bug

#361 Optimize off-screen content rendering using `content-visibility`
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
Labels: feature

#359 Render sidecar content only when on-screen
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/util/useOnScreen.ts
Labels: feature

#345 Replace old dev portal stuff with Zudoku
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/authentication/authentication.ts
  packages/zudoku/src/lib/components/DevPortal.tsx
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/components/context/ZudokuProvider.tsx
  packages/zudoku/src/lib/components/index.ts
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/plugins.ts
  packages/zudoku/src/lib/plugins/api-keys/index.tsx
  packages/zudoku/src/lib/plugins/custom-pages/index.tsx
  packages/zudoku/src/lib/plugins/markdown/index.tsx
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/redirect/index.tsx
  packages/zudoku/src/lib/plugins/search-inkeep/index.tsx
  packages/zudoku/src/types.d.ts
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: refactor, breaking-change

#368 GraphQL with react-query
  .gitattributes
  packages/zudoku/package.json
  packages/zudoku/project.json
  packages/zudoku/schema.graphql
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/codegen.ts
  packages/zudoku/src/lib/components/DeveloperHint.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
  packages/zudoku/src/lib/components/navigation/utils.ts
  packages/zudoku/src/lib/errors/ErrorAlert.tsx
  packages/zudoku/src/lib/plugins/openapi-worker.ts
  packages/zudoku/src/lib/plugins/openapi/Endpoint.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/Route.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLClient.tsx
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLContext.tsx
  packages/zudoku/src/lib/plugins/openapi/client/createMemoryClient.ts
  packages/zudoku/src/lib/plugins/openapi/client/createServer.ts
  packages/zudoku/src/lib/plugins/openapi/client/createWorkerClient.ts
  packages/zudoku/src/lib/plugins/openapi/client/interfaces.ts
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/client/worker.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/fragment-masking.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/util/createWaitForNotify.ts
  packages/zudoku/src/types.d.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/tsconfig.json
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
  scripts/package.json
  scripts/project.json
  scripts/tsconfig.json
Labels: refactor

#325 Allow static content generation in MDX files
  packages/zudoku/package.json
  packages/zudoku/src/vite/plugin-mdx.ts
  packages/zudoku/src/vite/remarkStaticGeneration.ts
  pnpm-lock.yaml
Labels: feature

#379 Fix GraphQL ↔ SharedWorker communication
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/lib/components/Bootstrap.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/plugins/openapi-worker.ts
  packages/zudoku/src/lib/plugins/openapi/ColorizedParam.tsx
  packages/zudoku/src/lib/plugins/openapi/Route.tsx
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLClient.tsx
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLContext.tsx
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/client/worker.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/util/createWaitForNotify.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/tsconfig.json
Labels: bug

#384 persist in localStorage
  packages/zudoku/package.json
  packages/zudoku/src/lib/authentication/hook.ts
  packages/zudoku/src/lib/authentication/providers/auth0.tsx
  packages/zudoku/src/lib/authentication/providers/openid.tsx
  packages/zudoku/src/lib/authentication/state.ts
Labels: feature

#388 Fix release notes body on update
  .github/release.yaml
  .github/workflows/release.js
Labels: bug, skip-changelog

#389 Delay spinner
  packages/zudoku/package.json
  packages/zudoku/src/lib/components/Layout.tsx
  pnpm-lock.yaml
Labels: feature

#391 Fix multiple imports in MDX static generation
  packages/zudoku/scripts/cli-dev.js
  packages/zudoku/src/vite/remarkStaticGeneration.ts
Labels: bug
