Repository zuplo/zudoku, pull requests merged in 2025-05, with the labels that each got.

#959 Check for working copy in build check
  packages/zudoku/src/lib/components/BuildCheck.tsx
Labels: skip-changelog, bug

#962 OpenAPI docs: Fix collapsible for param properties nullable arrays
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/utils.ts
Labels: bug

#956 Simplify config loading
  examples/with-zuplo/docs/dev-portal.json
  examples/with-zuplo/docs/zudoku.config.ts
  packages/config/.gitignore
  packages/config/README.md
  packages/config/package.json
  packages/config/project.json
  packages/config/scripts/build.mjs
  packages/config/src/index.d.ts
  packages/config/src/index.ts
  packages/config/tsconfig.json
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/vite/config.ts
  pnpm-lock.yaml
Labels: skip-changelog, maintenance

#980 Add support for `additionalProperties`
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
Labels: feature

#883 Use pnpm v10
  .github/workflows/build.yaml
  .github/workflows/main.yaml
  .tool-versions
  docs/package.json
  package.json
  pnpm-lock.yaml
Labels: maintenance

#881 Add support for RTL direction
  docs/src/ThemeEditor.tsx
  docs/zudoku.config.tsx
  packages/zudoku/src/app/main.css
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/Banner.tsx
  packages/zudoku/src/lib/components/Heading.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/Pagination.tsx
  packages/zudoku/src/lib/components/Search.tsx
  packages/zudoku/src/lib/components/navigation/PoweredByZudoku.tsx
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
  packages/zudoku/src/lib/components/navigation/Toc.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/plugins/openapi/CollapsibleCode.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/SchemaList.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/IdentitySelector.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/SubmitButton.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/RequestTab.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResponseTab.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResultPanel.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/ui/SyntaxHighlight.tsx
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/html.ts
Labels: feature

#987 allow to `disableSidecar` feature
  docs/pages/configuration/api-reference.md
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#988 Fix API catalog documentation
  docs/pages/configuration/api-catalog.md
Labels: docs

#994 Fix standalone mode
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/oas/parser/upgrade/index.ts
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/util/getRoutes.tsx
  packages/zudoku/src/lib/util/traverse.ts
Labels: bug

#995 Use correct stylesheet in standalone mode
  packages/zudoku/src/app/demo.html
Labels: bug

#996 Fix demo path rewrite
  website/next.config.mjs
Labels: skip-changelog, bug

#998 Remove autocomplete ring
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
Labels: skip-changelog, bug

#997 make the redirects work
  examples/cosmo-cargo/zudoku.config.tsx
  examples/with-auth0/zudoku.config.ts
  packages/zudoku/src/lib/authentication/components/CallbackHandler.tsx
  packages/zudoku/src/lib/authentication/providers/auth0.tsx
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
  packages/zudoku/src/lib/authentication/providers/openid.tsx
  packages/zudoku/src/lib/util/url.test.ts
  packages/zudoku/src/lib/util/url.ts
Labels: breaking-change

#999 Playground use same autocomplete styles
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
Labels: bug

#1000 OpenAPI: Improved code examples by adding required headers & query parameters
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
Labels: feature

#1006 Fix <hr> border color in prose
  packages/zudoku/src/app/main.css
Labels: bug

#1005 Relax `pageTitle` styles
  packages/zudoku/src/lib/components/Header.tsx
Labels: skip-changelog, maintenance

#1009 Change Zudoku console banner in Zuplo mode
  packages/zudoku/src/app/entry.client.tsx
Labels: skip-changelog

#1015 Node min version
  .tool-versions
  docs/pages/app-quickstart.md
  package.json
Labels: bug

#1002 Merge `allOf` for more consistent schemas
  examples/cosmo-cargo/schema/interplanetary.json
  packages/zudoku/package.json
  packages/zudoku/src/lib/oas/parser/index.ts
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaExampleAndDefault.tsx
  packages/zudoku/src/vite/api/SchemaManager.ts
  pnpm-lock.yaml
Labels: feature

#1008 OpenAPI: Fix circular schema
  .eslintrc.cjs
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/oas/graphql/circular.ts
  packages/zudoku/src/lib/plugins/openapi/ParamInfos.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/utils.ts
  packages/zudoku/src/lib/plugins/openapi/util/generateSchemaExample.ts
Labels: bug

#1007 Fix identity dialog labels
  packages/zudoku/package.json
  packages/zudoku/src/lib/plugins/openapi/playground/IdentitySelector.tsx
  pnpm-lock.yaml
Labels: bug

#1017 Check Node version
  docs/pages/app-quickstart.md
  package.json
  packages/zudoku/cli.js
  packages/zudoku/package.json
  pnpm-lock.yaml
Labels: maintenance

#1018 Test local publish and build "Cosmo Cargo" example
  .github/workflows/preview-build.yaml
  packages/zudoku/project.json
Labels: skip-changelog, maintenance

#1034 Fix React key issues in footer
  packages/zudoku/src/lib/components/Footer.tsx
Labels: bug

#1038 Dev config reload fixes
  examples/cosmo-cargo/pages/shipping-process.mdx
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
Labels: bug

#1040 Docs: Fix frontmatter `sidebar_icon` property
  docs/pages/configuration/navigation.mdx
Labels: docs

#1043 Reload config based on mtime
  packages/zudoku/src/config/common.ts
  packages/zudoku/src/config/config.ts
  packages/zudoku/src/config/file-exists.ts
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/components/Footer.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/plugins/markdown/index.tsx
  packages/zudoku/src/lib/plugins/markdown/resolver.ts
  packages/zudoku/src/lib/plugins/redirect/index.tsx
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/config.test.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/sitemap.ts
  packages/zudoku/src/zuplo/with-zuplo.ts
  packages/zudoku/vite.standalone.config.ts
Labels: maintenance

#1057 Allow prereleases for branches
  .github/workflows/branch-prerelease.yaml
  .github/workflows/preview-build.yaml
Labels: skip-changelog

#1059 Speed up internal dev start
  nx.json
  packages/zudoku/package.json
  packages/zudoku/project.json
  pnpm-lock.yaml
Labels: skip-changelog, maintenance

#1056 Rename interface
  packages/zudoku/src/lib/authentication/AuthenticationPlugin.tsx
  packages/zudoku/src/lib/authentication/authentication.ts
  packages/zudoku/src/lib/authentication/providers/auth0.tsx
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
  packages/zudoku/src/lib/authentication/providers/openid.tsx
  packages/zudoku/src/lib/authentication/providers/supabase.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/plugins.ts
  packages/zudoku/src/types.d.ts
Labels: skip-changelog

#1048 Extend Slot system
  docs/pages/components/slot.mdx
  docs/pages/configuration/footer.mdx
  docs/pages/configuration/slots.mdx
  docs/pages/configuration/vite-config.md
  docs/sidebar.ts
  docs/zudoku.config.tsx
  packages/zudoku/package.json
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/components/Footer.tsx
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/Slot.test.tsx
  packages/zudoku/src/lib/components/Slot.tsx
  packages/zudoku/src/lib/components/SlotletProvider.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/context/SlotProvider.tsx
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
  packages/zudoku/src/lib/components/navigation/utils.ts
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/plugins/api-keys/SettingsApiKeys.tsx
  packages/zudoku/src/lib/plugins/custom-pages/index.tsx
  packages/zudoku/src/lib/util/useExposedProps.tsx
  packages/zudoku/tsconfig.app.json
  packages/zudoku/vitest.config.ts
  packages/zudoku/vitest.setup.ts
  pnpm-lock.yaml
Labels: breaking-change, feature

#981 Upgrade Tailwind v4
  docs/src/ThemeEditor.tsx
  docs/src/baseColors/baseColors.ts
  packages/zudoku/package.json
  packages/zudoku/src/app/defaultTheme.css
  packages/zudoku/src/app/font.geist.css
  packages/zudoku/src/app/main.css
  packages/zudoku/src/app/tailwind.ts
  packages/zudoku/src/lib/components/Autocomplete.tsx
  packages/zudoku/src/lib/components/ErrorPage.tsx
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/InlineCode.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/NotFoundPage.tsx
  packages/zudoku/src/lib/components/Pagination.tsx
  packages/zudoku/src/lib/components/Search.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/PoweredByZudoku.tsx
  packages/zudoku/src/lib/components/navigation/SidebarBadge.tsx
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/components/navigation/SidebarWrapper.tsx
  packages/zudoku/src/lib/components/navigation/Toc.tsx
  packages/zudoku/src/lib/errors/ErrorAlert.tsx
  packages/zudoku/src/lib/plugins/api-catalog/Catalog.tsx
  packages/zudoku/src/lib/plugins/api-keys/CreateApiKey.tsx
  packages/zudoku/src/lib/plugins/api-keys/SettingsApiKeys.tsx
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/openapi/CollapsibleCode.tsx
  packages/zudoku/src/lib/plugins/openapi/ColorizedParam.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/SchemaList.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/components/EnumValues.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/PlaygroundDialog.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/SubmitButton.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaExampleAndDefault.tsx
  packages/zudoku/src/lib/ui/Badge.tsx
  packages/zudoku/src/lib/ui/Button.tsx
  packages/zudoku/src/lib/ui/Card.tsx
  packages/zudoku/src/lib/ui/Checkbox.tsx
  packages/zudoku/src/lib/ui/Command.tsx
  packages/zudoku/src/lib/ui/Dialog.tsx
  packages/zudoku/src/lib/ui/DropdownMenu.tsx
  packages/zudoku/src/lib/ui/HoverCard.tsx
  packages/zudoku/src/lib/ui/Input.tsx
  packages/zudoku/src/lib/ui/Popover.tsx
  packages/zudoku/src/lib/ui/RadioGroup.tsx
  packages/zudoku/src/lib/ui/Select.tsx
  packages/zudoku/src/lib/ui/Slider.tsx
  packages/zudoku/src/lib/ui/Switch.tsx
  packages/zudoku/src/lib/ui/Tabs.tsx
  packages/zudoku/src/lib/ui/Textarea.tsx
  packages/zudoku/src/lib/ui/Toggle.tsx
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-configure-tailwind.ts
  packages/zudoku/src/vite/plugin-theme-css.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/vite.standalone.config.ts
  pnpm-lock.yaml
Labels: dependencies, breaking-change, maintenance

#1061 Fix dev cmd
  packages/zudoku/package.json
  packages/zudoku/src/vite/config.ts
Labels: skip-changelog, bug

#1062 Fix flaky slot test
  packages/zudoku/src/lib/components/Slot.test.tsx
Labels: skip-changelog, bug

#1064 Export authentication plugin types
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/core/plugins.ts
Labels: bug

#1067 Simplify config reload mechanism
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/css/plugin.ts
  packages/zudoku/src/vite/plugin-api-keys.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-auth.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
  packages/zudoku/src/vite/plugin-config.ts
  packages/zudoku/src/vite/plugin-configure-tailwind.ts
  packages/zudoku/src/vite/plugin-custom-pages.ts
  packages/zudoku/src/vite/plugin-docs.test.ts
  packages/zudoku/src/vite/plugin-docs.ts
  packages/zudoku/src/vite/plugin-frontmatter.ts
  packages/zudoku/src/vite/plugin-mdx.ts
  packages/zudoku/src/vite/plugin-redirect.ts
  packages/zudoku/src/vite/plugin-search.ts
  packages/zudoku/src/vite/plugin-shiki-register.ts
  packages/zudoku/src/vite/plugin-sidebar.ts
  packages/zudoku/src/vite/plugin-theme-css.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/vite.standalone.config.ts
Labels: bug

#1071 Set CF account id for preview build
  .github/workflows/preview-build.yaml
Labels: skip-changelog, bug

#1070 Disable cache for playground mutation
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
Labels: bug

#1069 Handle multiple bundled CSS entries
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/html.ts
Labels: bug

#1072 Don't cache Playground requests
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
Labels: bug

#1076 Use anchor link icon for headings
  packages/zudoku/src/lib/components/Heading.tsx
Labels: feature
