Repository zuplo/zudoku, pull requests merged in 2025-01, with the labels that each got.

#443 Feat/category enhancements
  docs/pages/configuration/api-catalog.md
  docs/pages/configuration/api-reference.md
  docs/zudoku.config.tsx
  examples/godzilla-inc/zudoku.config.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/authentication/providers/openid.tsx
  packages/zudoku/src/lib/plugins/api-catalog/Catalog.tsx
  packages/zudoku/src/lib/plugins/api-catalog/index.tsx
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#176 Show full URL for method
  packages/zudoku/src/lib/components/navigation/SidebarBadge.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/util/methodToColor.ts
Labels: feature

#505 Return empty array instead of undefined for standalone
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#506 Fix: standalone by make `version` not required
  packages/zudoku/src/lib/plugins/openapi/Route.tsx
  packages/zudoku/src/lib/plugins/openapi/context.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
Labels: bug

#522 refactor(openapi): fix route version handling logic
  packages/zudoku/src/lib/plugins/openapi/index.tsx
Labels: bug

#515 feat: automatically fire browser on server start
  packages/zudoku/src/cli/cmds/dev.ts
  packages/zudoku/src/cli/dev/handler.ts
  packages/zudoku/src/vite/dev-server.ts
Labels: feature

#528 Export components
  packages/zudoku/src/lib/components/index.ts
Labels: feature

#527 Handle circular refs in OpenAPI schemas
  packages/zudoku/src/lib/oas/parser/dereference/index.ts
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaComponents.tsx
Labels: bug

#530 style: reduce transition duration for smoother animations
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  website/src/app/components/PreviewInput.tsx
  website/src/app/components/page.tsx
Labels: feature

#510 change sample project
  examples/godzilla-inc/pages/general.mdx
  examples/godzilla-inc/schema/destructive.json
  examples/godzilla-inc/schema/entertainment.json
  examples/godzilla-inc/schema/logistics.json
  examples/godzilla-inc/schema/logisticsV2.json
  examples/godzilla-inc/schema/operational.json
  examples/godzilla-inc/zudoku.config.ts
  examples/ship-happens/.gitignore
  examples/ship-happens/package.json
  examples/ship-happens/pages/burger.webp
  examples/ship-happens/pages/documentation/test.mdx
  examples/ship-happens/pages/general.mdx
  examples/ship-happens/pages/global.mdx
  examples/ship-happens/pages/intergalactic.mdx
  examples/ship-happens/pages/interstellar.mdx
  examples/ship-happens/public/burger.webp
  examples/ship-happens/public/header.png
  examples/ship-happens/public/header.webp
  examples/ship-happens/public/interstellar.png
  examples/ship-happens/public/space.webp
  examples/ship-happens/schema/interplanetary.json
  examples/ship-happens/schema/label-v1.json
  examples/ship-happens/schema/label-v2.json
  examples/ship-happens/schema/label-v3.json
  examples/ship-happens/schema/shipments.json
  examples/ship-happens/schema/webhooks.json
  examples/ship-happens/tsconfig.json
  examples/ship-happens/zudoku.config.tsx
  pnpm-lock.yaml
Labels: skip-changelog

#514 fix(generate-icon-types): correct path resolution for Windows base system
  packages/zudoku/scripts/generate-icon-types.ts
Labels: bug

#538 Render callback handler client only
  packages/zudoku/src/lib/authentication/providers/openid.tsx
Labels: bug

#537 Layout update
  docs/zudoku.config.tsx
  examples/ship-happens/zudoku.config.tsx
  packages/zudoku/src/app/main.css
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/SidebarWrapper.tsx
  packages/zudoku/src/lib/plugins/openapi/CollapsibleCode.tsx
  packages/zudoku/src/lib/plugins/openapi/Endpoint.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/SidecarBox.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/PlaygroundDialog.tsx
  packages/zudoku/src/lib/ui/Card.tsx
Labels: feature

#544 Implement user state management in Clerk provider
  examples/ship-happens/zudoku.config.tsx
  packages/zudoku/src/lib/authentication/components/SignOut.tsx
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
Labels: bug

#535 Add `cdnUrl` option
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/config.ts
Labels: feature

#557 Update search.md
  docs/pages/configuration/search.md
Labels: docs, skip-changelog

#545 Refactor schema loading
  packages/zudoku/package.json
  packages/zudoku/src/app/demo.tsx
  packages/zudoku/src/app/standalone.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi-worker.ts
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLClient.tsx
  packages/zudoku/src/lib/plugins/openapi/client/createServer.ts
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/client/worker.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/util/traverse.ts
  packages/zudoku/src/vite/api/schema-codegen.test.ts
  packages/zudoku/src/vite/api/schema-codegen.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/tsconfig.json
  packages/zudoku/vite.config.ts
  packages/zudoku/vite.standalone.config.ts
Labels: feature, refactor

#561 Fix example rendering
  examples/ship-happens/schema/shipments.json
  examples/ship-happens/zudoku.config.tsx
  packages/zudoku/src/lib/plugins/openapi/ExampleDisplay.tsx
  packages/zudoku/src/lib/plugins/openapi/RequestBodySidecarBox.tsx
  packages/zudoku/src/lib/plugins/openapi/ResponsesSidecarBox.tsx
  packages/zudoku/src/lib/plugins/openapi/SidecarExamples.tsx
  packages/zudoku/src/lib/plugins/openapi/util/generateSchemaExample.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#574 Dependency upgrades
  .gitattributes
  package.json
  packages/zudoku/package.json
  packages/zudoku/scripts/generate-icon-types.ts
  packages/zudoku/src/config/validators/icon-types.ts
  packages/zudoku/tsconfig.app.json
  packages/zudoku/tsconfig.json
  packages/zudoku/tsconfig.node.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#575 Revert sidebar category changes
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
Labels: bug

#525 Zuplo specific processors
  examples/ship-happens/schema/interplanetary.json
  examples/ship-happens/schema/label-v3.json
  examples/ship-happens/schema/shipments.json
  examples/ship-happens/schema/webhooks.json
  examples/with-zuplo/docs/.env.local
  examples/with-zuplo/docs/.gitignore
  examples/with-zuplo/docs/dev-portal.json
  examples/with-zuplo/docs/env.example
  examples/with-zuplo/docs/package.json
  examples/with-zuplo/docs/pages/introduction.mdx
  examples/with-zuplo/docs/project.json
  examples/with-zuplo/docs/tsconfig.json
  packages/zudoku/src/app/main.css
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/index.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeExtensions.test.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeExtensions.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeParameters.test.ts
  packages/zudoku/src/lib/plugins/openapi/post-processors/removeParameters.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/enrich-with-zuplo.ts
  packages/zudoku/src/zuplo/env.ts
  packages/zudoku/src/zuplo/policy-types.ts
  packages/zudoku/src/zuplo/with-zuplo-processors.ts
  packages/zudoku/src/zuplo/with-zuplo.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature

#564 Rework playground for usabilty & consistency
  examples/ship-happens/schema/label-v3.json
  examples/ship-happens/schema/webhooks.json
  examples/ship-happens/zudoku.config.tsx
  packages/zudoku/src/lib/components/Autocomplete.tsx
  packages/zudoku/src/lib/plugins/openapi/PlaygroundDialogWrapper.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/EnumSelector.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/ExamplesDropdown.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
  packages/zudoku/src/lib/ui/Command.tsx
Labels: feature

#586 Fix infinite redirect in dev
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#585 remove server build
  packages/zudoku/src/vite/build.ts
Labels: bug

#587 Add option `enableStatusPages` to generate http static pages
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/StatusPage.tsx
  packages/zudoku/src/zuplo/with-zuplo.ts
Labels: feature

#590 Fix Zuplo processors import
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/enrich-with-zuplo.ts
Labels: bug

#529 Allow to protect routes with login
  docs/pages/configuration/authentication.md
  docs/pages/configuration/overview.md
  examples/with-auth0/zudoku.config.ts
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/core/RouteGuard.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/vite/prerender.ts
Labels: feature

#591 Break up circular refs in GraphQL
  packages/zudoku/src/lib/oas/graphql/circular.ts
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/oas/parser/dereference/index.ts
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaComponents.tsx
Labels: bug

#577 Allow plugins to purge cache
  packages/zudoku/src/lib/components/cache.ts
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/components/index.ts
Labels: feature

#592 Improvements on Demo & Sample project
  examples/ship-happens/schema/label-v3.json
  examples/ship-happens/zudoku.config.tsx
Labels: skip-changelog

#601 Improve performance for pages with markdown
  packages/zudoku/src/lib/components/Markdown.tsx
Labels: feature

#604 fix title undefined
  packages/zudoku/src/lib/util/MdxComponents.tsx
Labels: bug

#607 Fix hash/anchor navigation synchronization
  packages/zudoku/src/lib/components/AnchorLink.tsx
  packages/zudoku/src/lib/components/context/ViewportAnchorContext.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/util/useScrollToAnchor.ts
Labels: bug

#609 Fix ThemeSwitch icon
  packages/zudoku/src/lib/components/ThemeSwitch.tsx
Labels: bug

#610 fix identy selection & headers
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/SubmitButton.tsx
Labels: skip-changelog

#611 Added doc section about user profile
  docs/pages/configuration/authentication.md
Labels: docs

#612 Added details on configuring identity providers
  docs/pages/configuration/authentication.md
Labels: docs

#614 Trigger update of Zuplo docs via Vercel webhook
  .github/workflows/docs.yaml
  .github/workflows/main.yaml
Labels: maintenance

#608 Cosmo Cargo Example
  examples/cosmo-cargo/.gitignore
  examples/cosmo-cargo/package.json
  examples/cosmo-cargo/pages/burger.webp
  examples/cosmo-cargo/pages/documentation/test.mdx
  examples/cosmo-cargo/pages/general.mdx
  examples/cosmo-cargo/pages/global.mdx
  examples/cosmo-cargo/pages/intergalactic.mdx
  examples/cosmo-cargo/pages/interstellar.mdx
  examples/cosmo-cargo/public/burger.webp
  examples/cosmo-cargo/public/header.png
  examples/cosmo-cargo/public/header.webp
  examples/cosmo-cargo/public/interstellar.png
  examples/cosmo-cargo/public/space.webp
  examples/cosmo-cargo/schema/interplanetary.json
  examples/cosmo-cargo/schema/label-v1.json
  examples/cosmo-cargo/schema/label-v2.json
  examples/cosmo-cargo/schema/label-v3.json
  examples/cosmo-cargo/schema/shipments.json
  examples/cosmo-cargo/schema/webhooks.json
  examples/cosmo-cargo/tsconfig.json
  examples/cosmo-cargo/vercel.json
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/src/vite/prerender.ts
  pnpm-lock.yaml
Labels: skip-changelog

#619 Revert docs primary color
  docs/zudoku.config.tsx
Labels: docs, skip-changelog

#618 Fix React hydration and key warnings
  packages/zudoku/src/lib/components/PathRenderer.tsx
  packages/zudoku/src/lib/components/ThemeSwitch.tsx
Labels: skip-changelog

#617 Fix clickable area in sidebar category
  packages/zudoku/src/lib/components/navigation/SidebarCategory.tsx
Labels: bug

#622 break long titles
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
Labels: bug

#625 Fix wrong context resolution
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/lib/components/index.ts
Labels: bug

#626 Playground header defaults
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/PlaygroundDialogWrapper.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/PlaygroundDialog.tsx
Labels: feature

#628 Fix dark/light theme config
  packages/zudoku/src/vite/plugin-theme-css.ts
Labels: bug

#630 Scroll initial sidebar item into view
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
  packages/zudoku/src/lib/util/scrollIntoViewIfNeeded.ts
  packages/zudoku/src/lib/util/useScrollToAnchor.ts
Labels: feature

#629 Filter tags that have no associated endpoints
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug
