Repository zuplo/zudoku, pull requests merged in 2025-07, with the labels that each got.

#1286 fix title
  packages/create-zudoku/templates/zuplo/pages/introduction.mdx
  packages/create-zudoku/templates/zuplo/zudoku.config.tsx
Labels: skip-changelog

#1318 Fix exposed doc pages must exist in navigation
  docs/pages/docs.md
  packages/zudoku/docs/build-processors.md
  packages/zudoku/src/config/validators/NavigationSchema.ts
  packages/zudoku/src/lib/components/NotFoundPage.tsx
  packages/zudoku/src/lib/errors/ErrorAlert.tsx
  packages/zudoku/src/vite/plugin-docs.ts
Labels: bug

#1319 Fix dev server `--open` argument
  packages/zudoku/src/vite/dev-server.ts
Labels: bug

#1323 Update OIDC callback url setup docs
  docs/pages/configuration/authentication.md
Labels: docs

#1322 Add `AGENT.md`
  .cursorrules
  AGENT.md
  CLAUDE.md
Labels: skip-changelog

#1339 Add JWT template name option on clerk auth
  docs/pages/configuration/authentication.md
  packages/zudoku/src/config/config.ts
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
Labels: feature

#1338 Allow callback for `display` for granular auth control
  examples/cosmo-cargo/pages/member-benefits.mdx
  examples/cosmo-cargo/pages/premium-fleet.mdx
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/src/config/validators/InputNavigationSchema.ts
  packages/zudoku/src/config/validators/ProtectedRoutesSchema.ts
  packages/zudoku/src/lib/authentication/hook.ts
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/NavigationItem.tsx
  packages/zudoku/src/lib/components/navigation/utils.ts
Labels: feature

#1357 Fix Windows path issue in docs resolution
  packages/zudoku/src/config/validators/NavigationSchema.ts
Labels: bug

#1363 Fix navigation category toggle hover color
  packages/zudoku/src/lib/components/navigation/NavigationCategory.tsx
Labels: bug

#1365 Fix: Custom Pages don't show the Navigation
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/components/navigation/NavigationItem.tsx
  packages/zudoku/src/lib/components/navigation/utils.ts
Labels: bug

#1366 Update clerk auth configuration
  docs/pages/configuration/authentication-clerk.md
Labels: docs

#1387 Move internals around
  packages/zudoku/package.json
  packages/zudoku/src/app/demo.tsx
  packages/zudoku/src/app/entry.client.tsx
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/app/standalone.tsx
  packages/zudoku/src/config/validators/ProtectedRoutesSchema.ts
  packages/zudoku/src/lib/components/index.ts
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/__internal.tsx
  packages/zudoku/src/lib/core/router.ts
  packages/zudoku/vite.config.ts
Labels: maintenance, bug

#1388 Fix `display` config in top navigation
  packages/zudoku/package.json
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/NavigationItem.tsx
  packages/zudoku/src/lib/components/navigation/utils.ts
  packages/zudoku/src/vite/plugin-navigation.ts
  pnpm-lock.yaml
Labels: bug

#1395 Add smoke test for preview publish
  .github/workflows/preview-build.yaml
Labels: maintenance

#1417 no more tabs
  docs/src/LandingPage.tsx
Labels: skip-changelog

#1428 Copy templates to build in `create-zudoku`
  .github/workflows/branch-prerelease.yaml
  packages/create-zudoku/package.json
Labels: bug

#1183 Improve documentation for components
  docs/package.json
  docs/pages/docs/components/alert.mdx
  docs/pages/docs/components/badge.mdx
  docs/pages/docs/components/button.mdx
  docs/pages/docs/components/callout.mdx
  docs/pages/docs/components/card.mdx
  docs/pages/docs/components/checkbox.mdx
  docs/pages/docs/components/client-only.mdx
  docs/pages/docs/components/dialog.mdx
  docs/pages/docs/components/head.mdx
  docs/pages/docs/components/icons.mdx
  docs/pages/docs/components/input.mdx
  docs/pages/docs/components/label.mdx
  docs/pages/docs/components/link.mdx
  docs/pages/docs/components/markdown.mdx
  docs/pages/docs/components/playground.mdx
  docs/pages/docs/components/secret.mdx
  docs/pages/docs/components/select.mdx
  docs/pages/docs/components/shadcn.mdx
  docs/pages/docs/components/slider.mdx
  docs/pages/docs/components/slot.mdx
  docs/pages/docs/components/stepper.mdx
  docs/pages/docs/components/switch.mdx
  docs/pages/docs/components/syntax-highlight.mdx
  docs/pages/docs/components/textarea.mdx
  docs/pages/docs/components/tooltip.mdx
  docs/pages/docs/components/typography.mdx
  docs/pages/docs/configuration/api-reference.md
  docs/pages/docs/customization/colors-theme.mdx
  docs/pages/docs/customization/fonts.md
  docs/sidebar.tsx
  docs/vite.config.ts
  examples/cosmo-cargo/pages/shipping-process.mdx
  packages/zudoku/src/lib/components/index.ts
  packages/zudoku/src/lib/ui/ReactComponentDoc.tsx
  pnpm-lock.yaml
Labels: docs, skip-changelog

#1431 Treat `.md` as plain Markdown
  examples/cosmo-cargo/pages/global.md
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: breaking-change, bug
