Repository zuplo/zudoku, pull requests merged in 2025-10, with the labels that each got.

#1580 Update auth0 guide to match names
  docs/pages/docs/configuration/authentication-auth0.md
Labels: docs, skip-changelog

#1588 Allow to approve preview build workflow for 3rd-party pull requests
  .github/workflows/preview-build.yaml
Labels: skip-changelog

#1589 Follow up #1588
  .github/workflows/main.yaml
  .github/workflows/preview-build.yaml
Labels: skip-changelog

#1591 Corrected quick-start URL
  README.md
Labels: approve public build

#1593 Fix: Allow remark/rehype plugins from build config
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: bug
