Repository zuplo/zudoku, pull requests merged in 2025-06, with the labels that each got.

#1080 Fix syntax highlight copy and empty lines
  packages/zudoku/src/app/main.css
Labels: bug

#1083 Fix callout/admonition code block overflow bug
  packages/zudoku/src/lib/ui/Callout.tsx
Labels: bug

#1133 fix lockfile
  pnpm-lock.yaml
Labels: skip-changelog

#1132 rename action
  .github/workflows/main.yaml
Labels: skip-changelog

#1136 Fix `zudoku/hooks` export
  packages/zudoku/package.json
Labels: bug

#1140 better image
  examples/with-zuplo/docs/pages/banner-dark.svg
  examples/with-zuplo/docs/pages/introduction.mdx
Labels: skip-changelog

#1161 Google tag manager exaple
  docs/pages/custom-plugins.md
Labels: docs

#1163 Update copy
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
Labels: skip-changelog

#1162 Remove image float
  examples/cosmo-cargo/pages/documentation.mdx
Labels: skip-changelog

#1160 Better theme support + shadcn registry
  docs/package.json
  docs/pages/customization/colors-theme.md
  docs/pages/customization/colors-theme.mdx
  docs/pages/customization/fonts.md
  docs/pages/customization/tweakcn0.webp
  docs/pages/customization/tweakcn1.webp
  docs/pages/customization/tweakcn2.webp
  docs/pages/customization/tweakcn3.webp
  docs/src/ThemeEditor.tsx
  packages/zudoku/src/app/defaultTheme.css
  packages/zudoku/src/app/entry.client.tsx
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/app/main.css
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/components/Framed.tsx
  packages/zudoku/src/lib/ui/CodeBlock.tsx
  packages/zudoku/src/lib/util/MdxComponents.tsx
  packages/zudoku/src/vite/css/plugin.ts
  packages/zudoku/src/vite/plugin-configure-tailwind.ts
  packages/zudoku/src/vite/plugin-mdx.ts
  packages/zudoku/src/vite/plugin-theme-css.ts
  packages/zudoku/src/vite/plugin-theme.test.ts
  packages/zudoku/src/vite/plugin-theme.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/src/vite/shadcn-registry.ts
  pnpm-lock.yaml
Labels: feature

#1166 Fix: correct issuer for clerk setups
  packages/zudoku/src/lib/auth/issuer.test.ts
  packages/zudoku/src/lib/auth/issuer.ts
Labels: skip-changelog

#1169 Add security warnings to prevent secrets exposure in docs
  docs/pages/configuration/overview.md
  docs/pages/guides/environment-variables.md
  docs/pages/guides/transforming-examples.md
Labels: docs

#1172 Fix OAuth callback route history
  packages/zudoku/src/lib/authentication/components/CallbackHandler.tsx
Labels: codex

#1170 Show delete button when API key has expiration
  packages/zudoku/src/lib/plugins/api-keys/SettingsApiKeys.tsx
Labels: codex

#1168 use array in default templates
  packages/create-zudoku-app/templates/default/js/zudoku.config.jsx
  packages/create-zudoku-app/templates/default/ts/zudoku.config.tsx
Labels: skip-changelog

#1182 finetune ui
  packages/zudoku/src/lib/plugins/api-keys/SettingsApiKeys.tsx
Labels: skip-changelog

#1188 fix redirect
  packages/create-zudoku-app/templates/default/js/zudoku.config.jsx
  packages/create-zudoku-app/templates/default/ts/zudoku.config.tsx
Labels: skip-changelog

#1187 add hints to file
  docs/pages/configuration/api-catalog.md
  docs/pages/configuration/api-reference.md
  docs/pages/configuration/overview.md
  docs/pages/customization/colors-theme.mdx
  docs/pages/customization/fonts.md
Labels: skip-changelog

#1192 Add Supabase auth docs
  docs/pages/configuration/authentication.md
Labels: codex

#1196 Update quickstart docs
  docs/pages/quickstart.md
  docs/sidebar.ts
  docs/zudoku.config.tsx
  packages/zudoku/src/app/main.css
Labels: docs

#1197 Error handling on API Keys
  packages/zudoku/src/lib/plugins/api-keys/SettingsApiKeys.tsx
  packages/zudoku/src/lib/plugins/api-keys/index.tsx
  packages/zudoku/src/lib/ui/Alert.tsx
Labels: skip-changelog

#1208 Add "last modified" and "suggest edit" features
  docs/pages/markdown/overview.md
  docs/pages/writing.mdx
  docs/sidebar.ts
  docs/zudoku.config.tsx
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/lib/components/Pagination.tsx
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/markdown/index.tsx
  packages/zudoku/src/lib/ui/CodeBlock.tsx
  packages/zudoku/src/vite/mdx/remark-last-modified.ts
  packages/zudoku/src/vite/mdx/utils.ts
  packages/zudoku/src/vite/plugin-frontmatter.ts
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: feature

#1215 Fix last modified timestamp to use author date
  packages/zudoku/src/vite/mdx/remark-last-modified.ts
Labels: bug

#1219 Support OpenAPI v3.1 `$ref` with sibling properties
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/vite/api/SchemaManager.ts
  packages/zudoku/src/vite/api/schema-codegen.test.ts
  packages/zudoku/src/vite/api/schema-codegen.ts
Labels: bug

#1222 Allow value `false` for `example` and `default`
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaExampleAndDefault.tsx
Labels: bug

#1221 Don't line clamp schema params
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
Labels: bug

#1184 Fix pagefind search base path
  docs/zudoku.config.tsx
  packages/zudoku/src/lib/components/Banner.tsx
  packages/zudoku/src/lib/components/CategoryHeading.tsx
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Pagination.tsx
  packages/zudoku/src/lib/components/navigation/NavigationWrapper.tsx
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/PagefindSearch.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/ResultList.tsx
  packages/zudoku/src/lib/ui/Alert.tsx
Labels: bug

#1282 Fix navigation docs
  docs/pages/configuration/navigation.mdx
Labels: docs
