Repository zuplo/zudoku, pull requests merged in 2025-04, with the labels that each got.

#855 Add schema list overview
  packages/zudoku/schema.graphql
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/navigation/Toc.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/oas/parser/dereference/index.ts
  packages/zudoku/src/lib/oas/parser/index.ts
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/openapi/SchemaList.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/util/getRoutes.tsx
  packages/zudoku/src/lib/util/useOnScreen.ts
  packages/zudoku/src/vite/api/schema-codegen.test.ts
  packages/zudoku/src/vite/api/schema-codegen.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#858 show badge for optional bodies
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
Labels: feature

#860 OpenAPI Docs Layout & Structure
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/SchemaList.tsx
Labels: skip-changelog

#859 Show schema examples in overview
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/ColorizedParam.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/components/EnumValues.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/LogicalGroup/LogicalGroup.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/LogicalGroup/LogicalGroupItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaExampleAndDefault.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/utils.ts
Labels: feature

#864 Pagefind search for protected routes
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/cli/cmds/dev.ts
  packages/zudoku/src/cli/dev/pagefind-command.ts
  packages/zudoku/src/lib/components/Bootstrap.tsx
  packages/zudoku/src/lib/components/context/BypassProtectedRoutesContext.ts
  packages/zudoku/src/lib/components/context/PluginSystem.ts
  packages/zudoku/src/lib/core/RouteGuard.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/PagefindSearch.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/ResultList.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/index.tsx
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/plugin-search.ts
  packages/zudoku/src/vite/prerender/FileWritingResponse.ts
  packages/zudoku/src/vite/prerender/InMemoryResponse.ts
  packages/zudoku/src/vite/prerender/PrerenderResponse.ts
  packages/zudoku/src/vite/prerender/prerender.ts
  packages/zudoku/src/vite/prerender/worker.ts
Labels: feature

#863 Make sure to run `initialize` only once
  packages/zudoku/src/lib/components/Zudoku.tsx
Labels: bug

#869 new banner
  examples/cosmo-cargo/pages/general.mdx
  examples/cosmo-cargo/pages/header.jpg
  examples/cosmo-cargo/pages/header.png
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/navigation/SidebarWrapper.tsx
Labels: skip-changelog

#876 fix-layout-next
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/PoweredByZudoku.tsx
Labels: skip-changelog, bug

#879 Fix array of objects in schema
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
Labels: bug

#882 Reload on outside OpenAPI file changes
  packages/zudoku/src/cli/build/handler.ts
  packages/zudoku/src/cli/dev/handler.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
Labels: bug

#887 Extend docs `basePath` and `cdnUrl`
  docs/pages/configuration/overview.md
Labels: docs, skip-changelog

#889 Fix ref lookup in schema codegen
  packages/zudoku/src/vite/api/schema-codegen.ts
Labels: bug

#890 API schema processors
  docs/pages/configuration/build-configuration.mdx
  docs/pages/guides/processors.mdx
  docs/sidebar.ts
  examples/cosmo-cargo/tsconfig.json
  examples/cosmo-cargo/zudoku.build.ts
  packages/zudoku/docs/build-processors.md
  packages/zudoku/package.json
  packages/zudoku/scripts/generate-icon-types.js
  packages/zudoku/src/config/config.ts
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/config/validators/BuildSchema.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeExtensions.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeExtensions.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeParameters.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeParameters.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removePaths.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removePaths.ts
  packages/zudoku/src/lib/plugins/openapi/processors/traverse.ts
  packages/zudoku/src/lib/ui/Callout.tsx
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/with-zuplo-processors.ts
  packages/zudoku/src/zuplo/with-zuplo.ts
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: feature

#897 Cosmo Cargo updates
  examples/cosmo-cargo/pages/documentation.mdx
  examples/cosmo-cargo/pages/shipping-process.mdx
  examples/cosmo-cargo/pages/tracking.mdx
  examples/cosmo-cargo/public/cosmo.webp
  examples/cosmo-cargo/src/Landingpage.tsx
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/src/app/main.css
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
  packages/zudoku/src/lib/components/Footer.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/util/MdxComponents.tsx
Labels: skip-changelog, bug

#898 Fix duplicate sidebar key
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
Labels: bug

#904 Package upgrades
  package.json
  packages/zudoku/package.json
  packages/zudoku/src/app/entry.client.tsx
  patches/vite@6.2.0.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: maintenance

#907 Revert remark-directive upgrade
  packages/zudoku/package.json
  pnpm-lock.yaml
Labels: bug

#909 Fix Zuplo base processors
  packages/zudoku/src/config/validators/BuildSchema.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeExtensions.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeExtensions.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeParameters.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removeParameters.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removePaths.test.ts
  packages/zudoku/src/lib/plugins/openapi/processors/removePaths.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/enrich-with-zuplo.ts
  packages/zudoku/src/zuplo/with-zuplo-processors.ts
Labels: bug

#912 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-changelog

#910 Reload sidebar when API schema changes
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-sidebar.ts
Labels: feature

#914 Zuplo integration
  packages/zudoku/client.d.ts
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/cli/common/machine-id/lib.ts
  packages/zudoku/src/config/ZuploBuildConfig.ts
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/env.d.ts
  packages/zudoku/src/lib/components/BuildCheck.tsx
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/index.ts
  packages/zudoku/src/lib/components/navigation/PoweredByZudoku.tsx
  packages/zudoku/src/lib/components/navigation/ZuploLogo.tsx
  packages/zudoku/src/vite-env.d.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/env.ts
  packages/zudoku/src/zuplo/with-zuplo.ts
Labels: feature

#923 Fix formatting
  docs/pages/configuration/overview.md
Labels: skip-changelog

#922 Add empty screen for API docs
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
Labels: feature

#925 Add `--zuplo` option
  examples/with-zuplo/docs/package.json
  packages/zudoku/src/cli/cli.ts
Labels: feature

#936 Fix URL based OpenAPI docs
  packages/zudoku/src/lib/oas/parser/index.ts
  packages/zudoku/src/lib/oas/parser/upgrade/index.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/util/getRoutes.tsx
Labels: bug

#939 Fix wrong auto-import
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#941 Move Zuplo env file
  packages/zudoku/src/app/ZuploBuildConfig.ts
  packages/zudoku/src/app/env.ts
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/zuplo/with-zuplo-processors.ts
Labels: bug

#944 Fix Windows schema import
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#949 Revert schema upgrade
  packages/zudoku/src/lib/oas/parser/index.ts
  packages/zudoku/src/lib/oas/parser/upgrade/index.ts
Labels: bug

#950 Make build check more error resilient
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/lib/components/BuildCheck.tsx
Labels: bug

#954 Updates to address security warnings
  package.json
  packages/zudoku/package.json
  pnpm-lock.yaml
Labels: maintenance

#955 Fix doc links
  docs/pages/components/syntax-highlight.mdx
  docs/pages/configuration/build-configuration.mdx
  docs/pages/guides/custom-pages.md
  docs/pages/guides/managing-api-keys-and-identities.md
  docs/pages/guides/processors.mdx
  docs/pages/guides/using-multiple-apis.md
  docs/pages/markdown/code-blocks.md
Labels: docs, skip-changelog
