Repository zuplo/zudoku, pull requests merged in 2025-08, with the labels that each got.

#1433 Bail if no React docgen
  packages/zudoku/src/lib/ui/ReactComponentDoc.tsx
Labels: skip-changelog, bug

#1432 Fix catalog hydration error
  packages/zudoku/src/lib/plugins/api-catalog/Catalog.tsx
Labels: bug

#1439 FIX: mixed localized dates and prefixes
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
Labels: bug

#1437 Use `x-displayName` in category title
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterList.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/PlaygroundDialogWrapper.tsx
  packages/zudoku/src/lib/plugins/openapi/RequestBodySidecarBox.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/SidecarExamples.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/fragment-masking.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/lib/plugins/openapi/playground/BodyPanel.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/ExamplesDropdown.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
Labels: bug

#1464 update zuplo readme to use zuplo links
  packages/create-zudoku/templates/zuplo/README-template.md
Labels: skip-changelog

#1471 Fix `x-displayName` in pagination
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
Labels: bug

#1434 Add support for MCP endpoints
  examples/cosmo-cargo/schema/ai-cargo.json
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/package.json
  packages/zudoku/src/app/main.css
  packages/zudoku/src/config/validators/icon-types.ts
  packages/zudoku/src/lib/plugins/openapi/MCPEndpoint.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/ui/CodeBlock.tsx
  pnpm-lock.yaml
Labels: feature
