Repository zuplo/zudoku, pull requests merged in 2025-03, with the labels that each got.

#765 Fixed a bug where the checkbox was fully round instead of square
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
  packages/zudoku/src/lib/ui/Checkbox.tsx
Labels: bug

#767 Fix layout jump in API docs
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
Labels: bug

#773 Playground: Make request cancelable by user
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResultPanel.tsx
Labels: feature

#775 Fix anchor link scroll for full paths
  packages/zudoku/src/lib/components/AnchorLink.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
Labels: bug

#776 Mark deprecated operations
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/util/MdxComponents.tsx
Labels: feature

#777 Playground: `Content-Type` defaults
  packages/zudoku/src/lib/plugins/openapi/playground/ExamplesDropdown.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/ui/Select.tsx
Labels: feature

#779 Playground: Disable code highlighting for large responses
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResponseTab.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResultPanel.tsx
  packages/zudoku/src/lib/ui/SyntaxHighlight.tsx
Labels: feature

#781 Use `loadConfigFromFile` to support import.meta.env in Zudoku config
  docs/pages/guides/environment-variables.md
  examples/with-zuplo/docs/.env.local
  package.json
  packages/zudoku/package.json
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/vite/config.ts
  patches/vite@6.2.0.patch
  pnpm-lock.yaml
Labels: bug

#780 Pagefind: Add command to create index for dev
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/cli/cmds/dev.ts
  packages/zudoku/src/cli/dev/pagefind-command.ts
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/create-pagefind-index.ts
Labels: feature

#782 Invalidate on schema changes
  packages/zudoku/src/config/common.ts
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#784 Improve prerender performance
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/prerender/prerender.ts
  packages/zudoku/src/vite/prerender/worker.ts
Labels: maintenance

#786 Use `runnerImport` instead of `loadConfigFromFile` to load Zudoku config
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/vite/config.ts
Labels: skip-changelog, maintenance

#790 Use Vite's own preview handler
  packages/zudoku/src/cli/preview/handler.ts
Labels: skip-changelog, maintenance

#799 OAS: Improve title and meta tags
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#801 Add Pagefind to docs
  docs/pages/components/callout.mdx
  docs/pages/configuration/search.md
  packages/zudoku/src/lib/ui/Callout.tsx
Labels: docs

#802 Fix auto login redirect with no `protectedRoutes`
  packages/zudoku/src/lib/core/RouteGuard.tsx
Labels: bug

#804 Simplify layout
  packages/zudoku/src/app/main.css
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/context/ViewportAnchorContext.tsx
  packages/zudoku/src/lib/components/navigation/Sidebar.tsx
  packages/zudoku/src/lib/components/navigation/SidebarWrapper.tsx
  packages/zudoku/src/lib/plugins/openapi/SimpleSelect.tsx
Labels: maintenance

#811 Allow to disable playground
  docs/pages/configuration/api-reference.md
  examples/cosmo-cargo/schema/shipments.json
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/schema.graphql
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#813 Fix OIDC redirect with origin
  examples/with-auth0/zudoku.config.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/authentication/providers/openid.tsx
Labels: bug

#814 Add `showVersionSelect` option
  docs/pages/configuration/api-reference.md
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#815 Show enum values
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/components/InlineCode.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/components/EnumValues.tsx
  packages/zudoku/src/lib/plugins/openapi/components/SelectOnClick.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
Labels: feature

#816 More layout fixes
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/errors/ErrorAlert.tsx
  packages/zudoku/src/lib/ui/SyntaxHighlight.tsx
Labels: skip-changelog, bug

#817 Fix spinner position
  packages/zudoku/src/lib/components/Layout.tsx
Labels: bug

#818 Add schema infos to params
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/ParamInfos.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/ui/Button.tsx
Labels: feature

#819 Show required everywhere instead of optional
  packages/zudoku/src/app/main.css
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/ParamInfos.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
Labels: feature

#820 OpenAPI docs: Simplify slugs
  packages/zudoku/package.json
  packages/zudoku/src/lib/components/AnchorLink.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  pnpm-lock.yaml
Labels: bug

#824 OpenAPI: Shows all tags (categories) with lightning speed ⚡
  docs/pages/configuration/api-reference.md
  packages/zudoku/schema.graphql
  packages/zudoku/src/app/entry.server.tsx
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/cache.ts
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/plugins.ts
  packages/zudoku/src/lib/hooks/useEvent.test.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/lib/plugins/openapi/util/createSidebarCategory.tsx
  packages/zudoku/src/lib/util/traverse.ts
  packages/zudoku/src/vite/api/schema-codegen.test.ts
  packages/zudoku/src/vite/api/schema-codegen.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: refactor, feature

#828 Add `expandAllTags` API option
  docs/pages/configuration/api-reference.md
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
Labels: feature

#833 Pass default `expandAllTags` option correctly
  docs/pages/configuration/api-reference.md
  packages/zudoku/src/vite/plugin-api.ts
Labels: bug

#834 Fix create-app template
  README.md
  packages/create-zudoku-app/templates/default/js/zudoku.config.mjs
  packages/create-zudoku-app/templates/default/ts/zudoku.config.ts
  packages/create-zudoku-app/templates/index.ts
  packages/zudoku/src/vite/config.ts
  website/src/app/components/Footer.tsx
Labels: bug

#837 Fix enum rendering
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/src/lib/plugins/openapi/ParamInfos.tsx
  packages/zudoku/src/lib/plugins/openapi/ParameterListItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaPropertyItem.tsx
  packages/zudoku/src/lib/plugins/openapi/schema/SchemaView.tsx
Labels: bug

#838 Fix: Use sidebar from top navigation if none other matches
  packages/zudoku/package.json
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/MobileTopNavigation.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/util/joinPath.tsx
  packages/zudoku/src/vite/plugin-docs.ts
  pnpm-lock.yaml
Labels: bug

#839 Fix multiple apis docs and example
  docs/pages/guides/using-multiple-apis.md
  examples/many-apis/download.js
  examples/many-apis/package.json
  examples/many-apis/pages/overview.mdx
  examples/many-apis/tsconfig.json
  examples/many-apis/zudoku.config.ts
  packages/zudoku/src/vite/api/schema-codegen.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: docs

#842 Fix initial anchor scroll
  packages/zudoku/src/lib/util/useScrollToAnchor.ts
Labels: bug

#845 Added event `auth` publishing changes to the auth state
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/plugins.ts
Labels: feature

#849 OpenAPI docs pagination
  packages/zudoku/package.json
  packages/zudoku/schema.graphql
  packages/zudoku/src/app/tailwind.ts
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/Main.tsx
  packages/zudoku/src/lib/components/Pagination.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/client/GraphQLClient.tsx
  packages/zudoku/src/lib/plugins/openapi/client/useCreateQuery.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/util/getRoutes.tsx
  packages/zudoku/src/vite/plugin-api.ts
  pnpm-lock.yaml
Labels: feature
