Repository zuplo/zudoku, pull requests merged in 2025-02, with the labels that each got.

#636 Add static files docs
  docs/pages/static-files.md
  docs/zudoku.config.tsx
Labels: docs

#627 Playground improvements
  packages/zudoku/src/lib/components/Autocomplete.tsx
  packages/zudoku/src/lib/components/PathRenderer.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Headers.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/ParamsGrid.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/PathParams.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/QueryParams.tsx
Labels: feature

#580 website: migrate tailwindcss v3 to v4
  pnpm-lock.yaml
  website/package.json
  website/postcss.config.mjs
  website/src/app/components/DocumentationButton.tsx
  website/src/app/components/FeatureGrid.tsx
  website/src/app/components/Footer.tsx
  website/src/app/components/OpenAPI.tsx
  website/src/app/components/PreviewInput.tsx
  website/src/app/components/TechStack.tsx
  website/src/app/components/page.tsx
  website/src/app/globals.css
  website/tailwind.config.ts
  website/tsconfig.json
Labels: maintenance

#642 Fall back to first server URL if persisted one does not exist
  packages/zudoku/src/lib/authentication/state.ts
  packages/zudoku/src/lib/plugins/openapi/Endpoint.tsx
  packages/zudoku/src/lib/plugins/openapi/OperationList.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
Labels: bug

#641 Allow relative paths in Markdown
  docs/pages/static-files.md
  examples/cosmo-cargo/pages/burger.webp
  examples/cosmo-cargo/pages/general.mdx
  examples/cosmo-cargo/pages/header.png
  examples/cosmo-cargo/pages/interstellar.mdx
  examples/cosmo-cargo/public/burger.webp
  examples/cosmo-cargo/public/header.png
  examples/cosmo-cargo/public/header.webp
  packages/zudoku/package.json
  packages/zudoku/src/vite/plugin-mdx.ts
  pnpm-lock.yaml
Labels: feature

#646 Expand categories for normal APIs
  examples/cosmo-cargo/schema/shipments.json
  packages/zudoku/schema.graphql
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/graphql.ts
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/interfaces.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: feature

#652 Better logging for prerendering
  packages/zudoku/src/lib/plugins/markdown/resolver.ts
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/prerender/prerender.ts
  packages/zudoku/src/vite/reporter.ts
Labels: bug

#654 Prerender optimizations
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/vite/prerender/prerender.ts
  packages/zudoku/src/vite/prerender/worker.ts
Labels: bug

#655 Fix examples may be null
  packages/zudoku/src/lib/oas/parser/upgrade/index.ts
Labels: bug

#657 Redirect back after sign-in
  examples/with-auth0/zudoku.config.ts
  packages/zudoku/src/lib/components/context/ZudokuContext.ts
  packages/zudoku/src/lib/core/RouteGuard.tsx
  packages/zudoku/src/lib/util/useLatest.ts
Labels: bug

#666 Imrpoved appearance switcher
  packages/zudoku/src/lib/components/ThemeSwitch.tsx
Labels: feature

#669 Support media assets for `cdnUrl` option
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-mdx.ts
Labels: feature

#670 Fix CDN url path join
  packages/zudoku/src/vite/config.ts
Labels: skip-changelog

#671 Fix basePath `/` path join
  packages/zudoku/src/vite/prerender/worker.ts
Labels: bug

#673 Fix schema node might be undefined
  packages/zudoku/src/vite/api/schema-codegen.ts
Labels: bug

#672 move sun down by one px
  packages/zudoku/src/lib/components/ThemeSwitch.tsx
Labels: skip-changelog

#664 Fix schemas with no prebuilt tag pages
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/OasProvider.tsx
  packages/zudoku/src/lib/plugins/openapi/OpenApiRoute.tsx
  packages/zudoku/src/lib/plugins/openapi/index.tsx
  packages/zudoku/src/lib/plugins/openapi/util/createSidebarCategory.tsx
  packages/zudoku/src/lib/plugins/openapi/util/getRoutes.tsx
  packages/zudoku/src/lib/plugins/openapi/util/methodColorMap.tsx
  packages/zudoku/src/vite/prerender/prerender.ts
Labels: bug

#677 Prerender redirects as static file or to Vercel config
  packages/zudoku/src/vite/build.ts
  packages/zudoku/src/vite/output.ts
  packages/zudoku/src/vite/prerender/FileWritingResponse.ts
  packages/zudoku/src/vite/prerender/prerender.ts
  packages/zudoku/src/vite/prerender/worker.ts
Labels: feature

#680 Add HTTPS support for dev server
  docs/pages/configuration/overview.md
  packages/zudoku/src/cli/common/utils/ports.ts
  packages/zudoku/src/cli/dev/handler.ts
  packages/zudoku/src/config/validators/common.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/error-handler.ts
Labels: feature

#698 fix duplicate icons ins set
  packages/zudoku/src/vite/plugin-sidebar.ts
Labels: bug

#699 Copy standalone CSS file
  packages/zudoku/package.json
Labels: bug

#700 Allow to set border radius in theme
  packages/zudoku/src/app/tailwind.ts
Labels: bug

#703 Reduce build warnings
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-api.ts
Labels: skip-changelog

#702 Update packages
  packages/zudoku/package.json
  packages/zudoku/src/config/validators/icon-types.ts
  packages/zudoku/src/lib/oas/graphql/index.ts
  packages/zudoku/src/lib/plugins/openapi/graphql/gql.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#707 Make layout the same width for all fonts
  packages/zudoku/src/lib/plugins/markdown/MdxPage.tsx
Labels: bug

#706 work on layout spacing
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
  packages/zudoku/src/lib/components/TopNavigation.tsx
  packages/zudoku/src/lib/components/navigation/SidebarWrapper.tsx
Labels: skip-changelog

#709 Add documentation for theming
  docs/pages/components/syntax-highlight.mdx
  docs/pages/customization/available-variables.mdx
  docs/sidebar.ts
  docs/src/PreviewBanner.tsx
  docs/src/ThemeEditor.tsx
  docs/src/baseColors/LICENSE.md
  docs/src/baseColors/baseColors.ts
  docs/zudoku.config.tsx
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
  packages/zudoku/src/lib/plugins/openapi/SidecarExamples.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/result-panel/ResponseTab.tsx
  packages/zudoku/src/lib/ui/SyntaxHighlight.tsx
  packages/zudoku/src/lib/ui/util.tsx
  packages/zudoku/src/lib/util/MdxComponents.tsx
Labels: docs

#712 add missing blank
  docs/src/PreviewBanner.tsx
Labels: skip-changelog

#711 Use plugin sidebar in API catalog plugin
  packages/zudoku/src/config/validators/InputSidebarSchema.ts
  packages/zudoku/src/lib/components/navigation/SidebarBadge.tsx
  packages/zudoku/src/lib/components/navigation/SidebarItem.tsx
  packages/zudoku/src/lib/plugins/api-catalog/Catalog.tsx
  packages/zudoku/src/lib/plugins/api-catalog/index.tsx
Labels: maintenance

#713 Fix mobile horizontal scroll
  packages/zudoku/src/lib/components/Header.tsx
  packages/zudoku/src/lib/components/Layout.tsx
Labels: bug

#715 Close Websocket on Vite server restart
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
Labels: bug

#716 Fix build warning for some environments
  packages/zudoku/src/vite/plugin-config.ts
Labels: bug

#719 use from config
  packages/zudoku/src/vite/build.ts
Labels: skip-changelog

#721 no timeout
  packages/zudoku/src/vite/prerender/prerender.ts
Labels: skip-changelog

#723 Dev server reload
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
Labels: bug

#725 learn from people in docs
  docs/zudoku.config.tsx
Labels: skip-changelog

#736 Fix multiple entries for `getHead` in plugins
  packages/zudoku/src/lib/components/Zudoku.tsx
Labels: bug

#730 Cleanup plugin options in favor of config meta
  packages/zudoku/src/cli/cli.ts
  packages/zudoku/src/config/common.ts
  packages/zudoku/src/config/config.ts
  packages/zudoku/src/config/loader.ts
  packages/zudoku/src/config/validators/validate.ts
  packages/zudoku/src/vite/config.test.ts
  packages/zudoku/src/vite/config.ts
  packages/zudoku/src/vite/css/plugin.ts
  packages/zudoku/src/vite/dev-server.ts
  packages/zudoku/src/vite/plugin-api-keys.ts
  packages/zudoku/src/vite/plugin-api.ts
  packages/zudoku/src/vite/plugin-auth.ts
  packages/zudoku/src/vite/plugin-component.ts
  packages/zudoku/src/vite/plugin-config-reload.ts
  packages/zudoku/src/vite/plugin-config.ts
  packages/zudoku/src/vite/plugin-custom-pages.ts
  packages/zudoku/src/vite/plugin-docs.ts
  packages/zudoku/src/vite/plugin-frontmatter.ts
  packages/zudoku/src/vite/plugin-mdx.ts
  packages/zudoku/src/vite/plugin-redirect.ts
  packages/zudoku/src/vite/plugin-search.ts
  packages/zudoku/src/vite/plugin-sidebar.ts
  packages/zudoku/src/vite/plugin-theme-css.ts
  packages/zudoku/src/vite/plugin.ts
  packages/zudoku/vite.standalone.config.ts
Labels: refactor

#708 Allow to consume events from Zudoku
  docs/pages/custom-plugins.md
  docs/pages/extending/events.md
  docs/sidebar.ts
  packages/zudoku/package.json
  packages/zudoku/src/app/main.tsx
  packages/zudoku/src/index.ts
  packages/zudoku/src/lib/components/Zudoku.tsx
  packages/zudoku/src/lib/components/context/RouterEventsProvider.tsx
  packages/zudoku/src/lib/core/ZudokuContext.ts
  packages/zudoku/src/lib/core/plugins.ts
  packages/zudoku/src/lib/hooks/index.ts
  packages/zudoku/src/lib/hooks/useEvent.test.tsx
  packages/zudoku/src/lib/hooks/useEvent.ts
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: feature

#746 Lint: Prefer type imports
  .eslintrc.cjs
Labels: maintenance

#748 Add `preview` command
  docs/package.json
  examples/api-identity-plugin/package.json
  examples/api-key-service/package.json
  examples/cosmo-cargo/package.json
  examples/with-auth0/package.json
  examples/with-config/package.json
  examples/with-openapi-json/package.json
  examples/with-openapi-yaml/package.json
  examples/with-vite-config/package.json
  examples/with-zuplo/docs/package.json
  nx.json
  packages/create-zudoku-app/templates/index.ts
  packages/zudoku/src/cli/build/handler.ts
  packages/zudoku/src/cli/cli.ts
  packages/zudoku/src/cli/cmds/build.ts
  packages/zudoku/src/cli/cmds/preview.ts
  packages/zudoku/src/cli/preview/handler.ts
Labels: feature

#751 Use custom OpenID scopes
  docs/pages/configuration/authentication.md
  packages/zudoku/src/config/config.ts
  packages/zudoku/src/lib/authentication/providers/auth0.tsx
  packages/zudoku/src/lib/authentication/providers/openid.tsx
Labels: bug

#749 Add `Stepper` component
  docs/pages/components/stepper.mdx
  docs/pages/components/syntax-highlight.mdx
  docs/pages/markdown/code-blocks.md
  docs/sidebar.ts
  packages/zudoku/cli.js
  packages/zudoku/package.json
  packages/zudoku/src/lib/ui/Stepper.css
  packages/zudoku/src/lib/ui/Stepper.tsx
  packages/zudoku/src/lib/util/MdxComponents.tsx
  pnpm-lock.yaml
Labels: feature

#752 fix schema
  examples/cosmo-cargo/schema/shipments.json
Labels: bug, skip-changelog

#754 fix line height for overlapping
  packages/zudoku/src/lib/plugins/openapi/Sidecar.tsx
Labels: bug

#756 don't redirect while pending
  examples/cosmo-cargo/zudoku.config.tsx
  packages/zudoku/src/lib/authentication/state.ts
  packages/zudoku/src/lib/core/RouteGuard.tsx
Labels: bug, skip-changelog

#755 Fix sort order of params in Playground
  packages/zudoku/src/lib/plugins/openapi/playground/PathParams.tsx
  packages/zudoku/src/lib/plugins/openapi/playground/Playground.tsx
Labels: bug

#757 Fix auth redirect for Clerk
  packages/zudoku/src/lib/authentication/providers/clerk.tsx
Labels: bug

#761 Pagefind fixes
  packages/zudoku/package.json
  packages/zudoku/src/lib/plugins/search-pagefind/PagefindSearch.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/ResultList.tsx
  packages/zudoku/src/lib/plugins/search-pagefind/index.tsx
  packages/zudoku/src/vite/plugin-search.ts
  packages/zudoku/vite.config.ts
  pnpm-lock.yaml
Labels: bug, skip-changelog
